config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :prospects, only: [:new, :create]
  resources :report_recipients
  resources :reports
  resources :air_quality_readings
  resources :symptom_logs
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/symptom_log.rb
# == Schema Information
#
# Table name: symptom_logs
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  symptom    :string
#  severity   :integer
#  log_time   :datetime
#  notes      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SymptomLog < ApplicationRecord
  belongs_to :user
end

app/controllers/symptom_logs_controller.rb
class SymptomLogsController < ApplicationController
  before_action :set_symptom_log, only: %i[ show edit update destroy ]

  # GET /symptom_logs or /symptom_logs.json
  def index
    @symptom_logs = SymptomLog.all
  end

  # GET /symptom_logs/1 or /symptom_logs/1.json
  def show
  end

  # GET /symptom_logs/new
  def new
    @symptom_log = SymptomLog.new
  end

  # GET /symptom_logs/1/edit
  def edit
  end

  # POST /symptom_logs or /symptom_logs.json
  def create
    @symptom_log = SymptomLog.new(symptom_log_params)

    respond_to do |format|
      if @symptom_log.save
        format.html { redirect_to @symptom_log, notice: "Symptom log was successfully created." }
        format.json { render :show, status: :created, location: @symptom_log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @symptom_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /symptom_logs/1 or /symptom_logs/1.json
  def update
    respond_to do |format|
      if @symptom_log.update(symptom_log_params)
        format.html { redirect_to @symptom_log, notice: "Symptom log was successfully updated." }
        format.json { render :show, status: :ok, location: @symptom_log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @symptom_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /symptom_logs/1 or /symptom_logs/1.json
  def destroy
    @symptom_log.destroy!

    respond_to do |format|
      format.html { redirect_to symptom_logs_path, status: :see_other, notice: "Symptom log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_symptom_log
      @symptom_log = SymptomLog.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def symptom_log_params
      params.expect(symptom_log: [ :user_id, :symptom, :severity, :log_time, :notes ])
    end
end

app/helpers/symptom_logs_helper.rb
module SymptomLogsHelper
end

app/views/symptom_logs/_form.html.erb
<%= form_with(model: symptom_log) do |form| %>
  <% if symptom_log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(symptom_log.errors.count, "error") %> prohibited this symptom_log from being saved:</h2>

      <ul>
        <% symptom_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :symptom, style: "display: block" %>
    <%= form.text_field :symptom %>
  </div>

  <div>
    <%= form.label :severity, style: "display: block" %>
    <%= form.number_field :severity %>
  </div>

  <div>
    <%= form.label :log_time, style: "display: block" %>
    <%= form.datetime_field :log_time %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.textarea :notes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/symptom_logs/_symptom_log.html.erb
<div id="<%= dom_id symptom_log %>">
  <p>
    <strong>User:</strong>
    <%= symptom_log.user_id %>
  </p>

  <p>
    <strong>Symptom:</strong>
    <%= symptom_log.symptom %>
  </p>

  <p>
    <strong>Severity:</strong>
    <%= symptom_log.severity %>
  </p>

  <p>
    <strong>Log time:</strong>
    <%= symptom_log.log_time %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= symptom_log.notes %>
  </p>

</div>

app/views/symptom_logs/edit.html.erb
<% content_for :title, "Editing symptom log" %>

<h1>Editing symptom log</h1>

<%= render "form", symptom_log: @symptom_log %>

<br>

<div>
  <%= link_to "Show this symptom log", @symptom_log %> |
  <%= link_to "Back to symptom logs", symptom_logs_path %>
</div>

app/views/symptom_logs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Symptom logs" %>

<h1>Symptom logs</h1>

<div id="symptom_logs">
  <% @symptom_logs.each do |symptom_log| %>
    <%= render symptom_log %>
    <p>
      <%= link_to "Show this symptom log", symptom_log %>
    </p>
  <% end %>
</div>

<%= link_to "New symptom log", new_symptom_log_path %>

app/views/symptom_logs/new.html.erb
<% content_for :title, "New symptom log" %>

<h1>New symptom log</h1>

<%= render "form", symptom_log: @symptom_log %>

<br>

<div>
  <%= link_to "Back to symptom logs", symptom_logs_path %>
</div>

app/views/symptom_logs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @symptom_log %>

<div>
  <%= link_to "Edit this symptom log", edit_symptom_log_path(@symptom_log) %> |
  <%= link_to "Back to symptom logs", symptom_logs_path %>

  <%= button_to "Destroy this symptom log", @symptom_log, method: :delete %>
</div>