config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :prospects, only: [:new, :create]
  resources :report_recipients
  resources :reports
  resources :air_quality_readings
  resources :symptom_logs
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/report_recipient.rb
# == Schema Information
#
# Table name: report_recipients
#
#  id         :integer          not null, primary key
#  report_id  :integer          not null
#  email      :string
#  role       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ReportRecipient < ApplicationRecord
  belongs_to :report
end

app/controllers/report_recipients_controller.rb
class ReportRecipientsController < ApplicationController
  before_action :set_report_recipient, only: %i[ show edit update destroy ]

  # GET /report_recipients or /report_recipients.json
  def index
    @report_recipients = ReportRecipient.all
  end

  # GET /report_recipients/1 or /report_recipients/1.json
  def show
  end

  # GET /report_recipients/new
  def new
    @report_recipient = ReportRecipient.new
  end

  # GET /report_recipients/1/edit
  def edit
  end

  # POST /report_recipients or /report_recipients.json
  def create
    @report_recipient = ReportRecipient.new(report_recipient_params)

    respond_to do |format|
      if @report_recipient.save
        format.html { redirect_to @report_recipient, notice: "Report recipient was successfully created." }
        format.json { render :show, status: :created, location: @report_recipient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report_recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /report_recipients/1 or /report_recipients/1.json
  def update
    respond_to do |format|
      if @report_recipient.update(report_recipient_params)
        format.html { redirect_to @report_recipient, notice: "Report recipient was successfully updated." }
        format.json { render :show, status: :ok, location: @report_recipient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report_recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_recipients/1 or /report_recipients/1.json
  def destroy
    @report_recipient.destroy!

    respond_to do |format|
      format.html { redirect_to report_recipients_path, status: :see_other, notice: "Report recipient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report_recipient
      @report_recipient = ReportRecipient.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def report_recipient_params
      params.expect(report_recipient: [ :report_id, :email, :role ])
    end
end

app/helpers/report_recipients_helper.rb
module ReportRecipientsHelper
end

app/views/report_recipients/_form.html.erb
<%= form_with(model: report_recipient) do |form| %>
  <% if report_recipient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(report_recipient.errors.count, "error") %> prohibited this report_recipient from being saved:</h2>

      <ul>
        <% report_recipient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :report_id, style: "display: block" %>
    <%= form.text_field :report_id %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/report_recipients/_report_recipient.html.erb
<div id="<%= dom_id report_recipient %>">
  <p>
    <strong>Report:</strong>
    <%= report_recipient.report_id %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= report_recipient.email %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= report_recipient.role %>
  </p>

</div>

app/views/report_recipients/edit.html.erb
<% content_for :title, "Editing report recipient" %>

<h1>Editing report recipient</h1>

<%= render "form", report_recipient: @report_recipient %>

<br>

<div>
  <%= link_to "Show this report recipient", @report_recipient %> |
  <%= link_to "Back to report recipients", report_recipients_path %>
</div>

app/views/report_recipients/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Report recipients" %>

<h1>Report recipients</h1>

<div id="report_recipients">
  <% @report_recipients.each do |report_recipient| %>
    <%= render report_recipient %>
    <p>
      <%= link_to "Show this report recipient", report_recipient %>
    </p>
  <% end %>
</div>

<%= link_to "New report recipient", new_report_recipient_path %>

app/views/report_recipients/new.html.erb
<% content_for :title, "New report recipient" %>

<h1>New report recipient</h1>

<%= render "form", report_recipient: @report_recipient %>

<br>

<div>
  <%= link_to "Back to report recipients", report_recipients_path %>
</div>

app/views/report_recipients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @report_recipient %>

<div>
  <%= link_to "Edit this report recipient", edit_report_recipient_path(@report_recipient) %> |
  <%= link_to "Back to report recipients", report_recipients_path %>

  <%= button_to "Destroy this report recipient", @report_recipient, method: :delete %>
</div>