config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :prospects, only: [:new, :create]
  resources :report_recipients
  resources :reports
  resources :air_quality_readings
  resources :symptom_logs
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/air_quality_reading.rb
# == Schema Information
#
# Table name: air_quality_readings
#
#  id         :integer          not null, primary key
#  timestamp  :datetime
#  aqi        :integer
#  source     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AirQualityReading < ApplicationRecord
end

app/controllers/air_quality_readings_controller.rb
class AirQualityReadingsController < ApplicationController
  before_action :set_air_quality_reading, only: %i[ show edit update destroy ]

  # GET /air_quality_readings or /air_quality_readings.json
  def index
    @air_quality_readings = AirQualityReading.all
  end

  # GET /air_quality_readings/1 or /air_quality_readings/1.json
  def show
  end

  # GET /air_quality_readings/new
  def new
    @air_quality_reading = AirQualityReading.new
  end

  # GET /air_quality_readings/1/edit
  def edit
  end

  # POST /air_quality_readings or /air_quality_readings.json
  def create
    @air_quality_reading = AirQualityReading.new(air_quality_reading_params)

    respond_to do |format|
      if @air_quality_reading.save
        format.html { redirect_to @air_quality_reading, notice: "Air quality reading was successfully created." }
        format.json { render :show, status: :created, location: @air_quality_reading }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @air_quality_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /air_quality_readings/1 or /air_quality_readings/1.json
  def update
    respond_to do |format|
      if @air_quality_reading.update(air_quality_reading_params)
        format.html { redirect_to @air_quality_reading, notice: "Air quality reading was successfully updated." }
        format.json { render :show, status: :ok, location: @air_quality_reading }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @air_quality_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /air_quality_readings/1 or /air_quality_readings/1.json
  def destroy
    @air_quality_reading.destroy!

    respond_to do |format|
      format.html { redirect_to air_quality_readings_path, status: :see_other, notice: "Air quality reading was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_air_quality_reading
      @air_quality_reading = AirQualityReading.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def air_quality_reading_params
      params.expect(air_quality_reading: [ :timestamp, :aqi, :source ])
    end
end

app/helpers/air_quality_readings_helper.rb
module AirQualityReadingsHelper
end

app/views/air_quality_readings/_air_quality_reading.html.erb
<div id="<%= dom_id air_quality_reading %>">
  <p>
    <strong>Timestamp:</strong>
    <%= air_quality_reading.timestamp %>
  </p>

  <p>
    <strong>Aqi:</strong>
    <%= air_quality_reading.aqi %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= air_quality_reading.source %>
  </p>

</div>

app/views/air_quality_readings/_form.html.erb
<%= form_with(model: air_quality_reading) do |form| %>
  <% if air_quality_reading.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(air_quality_reading.errors.count, "error") %> prohibited this air_quality_reading from being saved:</h2>

      <ul>
        <% air_quality_reading.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :timestamp, style: "display: block" %>
    <%= form.datetime_field :timestamp %>
  </div>

  <div>
    <%= form.label :aqi, style: "display: block" %>
    <%= form.number_field :aqi %>
  </div>

  <div>
    <%= form.label :source, style: "display: block" %>
    <%= form.text_field :source %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/air_quality_readings/edit.html.erb
<% content_for :title, "Editing air quality reading" %>

<h1>Editing air quality reading</h1>

<%= render "form", air_quality_reading: @air_quality_reading %>

<br>

<div>
  <%= link_to "Show this air quality reading", @air_quality_reading %> |
  <%= link_to "Back to air quality readings", air_quality_readings_path %>
</div>

app/views/air_quality_readings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Air quality readings" %>

<h1>Air quality readings</h1>

<div id="air_quality_readings">
  <% @air_quality_readings.each do |air_quality_reading| %>
    <%= render air_quality_reading %>
    <p>
      <%= link_to "Show this air quality reading", air_quality_reading %>
    </p>
  <% end %>
</div>

<%= link_to "New air quality reading", new_air_quality_reading_path %>

app/views/air_quality_readings/new.html.erb
<% content_for :title, "New air quality reading" %>

<h1>New air quality reading</h1>

<%= render "form", air_quality_reading: @air_quality_reading %>

<br>

<div>
  <%= link_to "Back to air quality readings", air_quality_readings_path %>
</div>

app/views/air_quality_readings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @air_quality_reading %>

<div>
  <%= link_to "Edit this air quality reading", edit_air_quality_reading_path(@air_quality_reading) %> |
  <%= link_to "Back to air quality readings", air_quality_readings_path %>

  <%= button_to "Destroy this air quality reading", @air_quality_reading, method: :delete %>
</div>